export default {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#c6c6c7",
        "primary-container": "#ffffff",
        "tertiary-fixed": "#e2e2e2",
        "surface-bright": "#fcf8f8",
        "on-primary-fixed-variant": "#454747",
        "outline-variant": "#c4c7c8",
        "surface-dim": "#ddd9d9",
        "secondary-fixed": "#e2e2e2",
        "primary-fixed-dim": "#c6c6c7",
        primary: "#5d5f5f",
        "on-surface-variant": "#444748",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#e5e2e1",
        surface: "#fcf8f8",
        "secondary-fixed-dim": "#c6c6c7",
        "surface-container": "#f1edec",
        "on-tertiary-container": "#747676",
        "surface-tint": "#5d5f5f",
        "surface-container-low": "#f6f3f2",
        "surface-container-high": "#ebe7e7",
        "primary-fixed": "#e2e2e2",
        "on-primary-fixed": "#1a1c1c",
        "on-background": "#1c1b1b",
        "tertiary-container": "#ffffff",
        background: "#fcf8f8",
        outline: "#747878",
        "inverse-surface": "#313030",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#1a1c1c",
        "on-primary": "#ffffff",
        "on-surface": "#1c1b1b",
        error: "#ba1a1a",
        "secondary-container": "#dcdddd",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#454747",
        "on-error-container": "#93000a",
        "inverse-primary": "#c6c6c7",
        "on-secondary-container": "#5f6161",
        tertiary: "#5d5f5f",
        "inverse-on-surface": "#f4f0ef",
        "error-container": "#ffdad6",
        "on-tertiary-fixed": "#1a1c1c",
        "surface-variant": "#e5e2e1",
        secondary: "#5d5f5f",
        "on-secondary-fixed-variant": "#454747",
        "on-primary-container": "#747676",
        "amber-500": "#f59e0b",
        "amber-600": "#d97706",
      },
      spacing: {
        unit: "8px",
        "polaroid-padding-top": "10px",
        "polaroid-padding-bottom": "56px",
        "wall-margin": "10vw",
        "gallery-gap": "4rem",
      },
      fontFamily: {
        "polaroid-title": ["Newsreader", "serif"],
        "brand-display": ["Pinyon Script", "cursive"],
        "section-cursive": ["Pinyon Script", "cursive"],
        "metadata-caps": ["Inter", "sans-serif"],
        "body-elegant": ["Newsreader", "serif"],
      },
      fontSize: {
        "polaroid-title": [
          "14px",
          { lineHeight: "1.2", fontWeight: "400" },
        ],
        "brand-display": [
          "4rem",
          { lineHeight: "1.2", fontWeight: "400" },
        ],
        "section-cursive": [
          "3rem",
          { lineHeight: "1.2", fontWeight: "400" },
        ],
        "metadata-caps": [
          "10px",
          {
            lineHeight: "1rem",
            letterSpacing: "0.15em",
            fontWeight: "500",
          },
        ],
        "body-elegant": [
          "18px",
          { lineHeight: "1.6", fontWeight: "400" },
        ],
      },
    },
  },
};
